import Head from 'next/head';
import CardList from '../components/CardList';


export default function Home() {
  return (
    <>
      <Head>
        <title>Bankless Stack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1 className='bg-red-700'>Bankless Stack</h1>
        </div>

        <div>
          <p>BanklessDAO dev Guild</p>
        </div>
        <div>
          <CardList />
        </div>
      </main>
    </>
  );
}
