import Head from 'next/head';
import CardList from '../components/CardList';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bankless Stack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen pt-10">
        <div className='mb-40'>
          <div>
            <h1 className="text-6xl font-bold text-center text-red-700">
              Bankless Stack
            </h1>
          </div>

          <div className="text-white text-center">
            <p>BanklessDAO dev Guild</p>
          </div>
        </div>
        <div className="flex justify-center flex-wrap">
          <CardList />
        </div>
      </main>
    </>
  );
}
